export type DashboardHoldingRow = {
  id: number;
  organisationId: number;
  organisationName: string;
  ownerId: number;
  ownerName: string;
  accountId: number;
  accountName: string;
  benchmark: string | null;
  dealId: number;
  dealSlug: string;
  dealName: string;
  borrower: string;
  grade: string;
  watchlist: boolean;
  exposure: number;
  reportedDscr: number | null;
  covenantStatus: string;
  distributionStatus: string | null;
  distributionBlockerCount: number;
  overdueObligations: number;
  deliverablesUpToDate: boolean;
  pendingReviews: number;
  reviewStatus: string;
  performanceScore: number | null;
  performanceSummary: string | null;
  watchlistRecommendation: string | null;
  escalationLevel: string | null;
  forecastedDscr: number | null;
  forecastCaseCount: number;
  forecastSummary: string | null;
  openRequests: number;
  highPriorityRequests: number;
  requestsWithOpposition: number;
  governanceSummary: string;
};

export type DashboardDealRow = {
  dealId: number;
  dealSlug: string;
  dealName: string;
  borrower: string;
  grade: string;
  watchlist: boolean;
  exposure: number;
  reportedDscr: number | null;
  covenantStatus: string;
  distributionStatus: string | null;
  distributionBlockerCount: number;
  overdueObligations: number;
  deliverablesUpToDate: boolean;
  pendingReviews: number;
  reviewStatus: string;
  performanceScore: number | null;
  performanceSummary: string | null;
  watchlistRecommendation: string | null;
  escalationLevel: string | null;
  forecastedDscr: number | null;
  forecastCaseCount: number;
  forecastSummary: string | null;
  openRequests: number;
  highPriorityRequests: number;
  requestsWithOpposition: number;
  governanceSummary: string;
  organisations: string[];
  owners: string[];
  accounts: string[];
};

export type DashboardResponse = {
  viewer: {
    displayName: string;
    teamName: string;
    roleNames: string[];
    permissionKeys: string[];
    permissions: {
      canViewPortfolio: boolean;
      canViewDeal: boolean;
      canViewReports: boolean;
      canViewActivity: boolean;
      canGenerateReports: boolean;
      canReviewReports: boolean;
      canApproveReports: boolean;
      canReleaseReports: boolean;
      canDecideRequests: boolean;
      canCaptureSnapshots: boolean;
    };
    entitlementSummaries: string[];
  };
  platformClient: {
    id: number;
    name: string;
    clientType: string;
  };
  summary: {
    totalExposure: number;
    dealCount: number;
    organisationCount: number;
    ownerCount: number;
    accountCount: number;
    pendingReviews: number;
    overdueObligations: number;
    openRequests: number;
    watchlistCount: number;
    restrictedDealCount: number;
    blockedDealCount: number;
  };
  holdings: DashboardHoldingRow[];
  deals: DashboardDealRow[];
};
